#!/bin/bash

#                                                                                
#    Copyright 2014-2015                                                         
#                                                                                
#      STIC-Investigación - Universidad de La Laguna (ULL) <gesinv@ull.edu.es>   
#                                                                                
#    This file is part of Portal del Investigador.                               
#                                                                                
#    Portal del Investigador is free software: you can redistribute it and/or       
#    modify it under the terms of the GNU Affero General Public License as          
#    published by the Free Software Foundation, either version 3 of the          
#    License, or (at your option) any later version.                             
#                                                                                
#    Portal del Investigador is distributed in the hope that it will be useful,  
#    but WITHOUT ANY WARRANTY; without even the implied warranty of              
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               
#    GNU Affero General Public License for more details.                         
#                                                                                
#    You should have received a copy of the GNU Affero General Public License       
#    along with Portal del Investigador.  If not, see                            
#    <http://www.gnu.org/licenses/>.                                             
#

echo "Checking for new or changed submodules..."

ROOT_DIR=$(git rev-parse --show-toplevel)
SUBMODULES=$(grep path ${ROOT_DIR}/.gitmodules | sed 's/^.*path = //')

# Find new submodules
NEW_SUBMODULES=$(git submodule status | egrep '^-' | cut -f2 -d' ')

if [[ "$NEW_SUBMODULES" ]]; then
    echo "$NEW_SUBMODULES"
    git submodule init
fi
git submodule sync
git submodule update

