# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.TextField(null=True, verbose_name='Publication title', blank=True)),
                ('fecha', models.DateField(null=True, verbose_name='Date', blank=True)),
                ('nombre_publicacion', models.TextField(null=True, verbose_name='Publication name', blank=True)),
                ('volumen', models.CharField(max_length=100, null=True, verbose_name='Volume', blank=True)),
                ('numero', models.CharField(max_length=100, null=True, verbose_name='Number', blank=True)),
                ('pagina_inicial', models.CharField(max_length=100, null=True, verbose_name='First page', blank=True)),
                ('pagina_final', models.CharField(max_length=100, null=True, verbose_name='Last page', blank=True)),
                ('autores', models.TextField(null=True, verbose_name='Authors', blank=True)),
                ('isbn', models.CharField(max_length=150, null=True, verbose_name='ISBN', blank=True)),
                ('issn', models.CharField(max_length=150, null=True, verbose_name='ISSN', blank=True)),
                ('deposito_legal', models.CharField(max_length=150, null=True, verbose_name='Legal deposit', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.TextField(null=True, verbose_name='Publication title', blank=True)),
                ('fecha', models.DateField(null=True, verbose_name='Date', blank=True)),
                ('nombre_publicacion', models.TextField(null=True, verbose_name='Publication name', blank=True)),
                ('volumen', models.CharField(max_length=100, null=True, verbose_name='Volume', blank=True)),
                ('numero', models.CharField(max_length=100, null=True, verbose_name='Number', blank=True)),
                ('pagina_inicial', models.CharField(max_length=100, null=True, verbose_name='First page', blank=True)),
                ('pagina_final', models.CharField(max_length=100, null=True, verbose_name='Last page', blank=True)),
                ('autores', models.TextField(null=True, verbose_name='Authors', blank=True)),
                ('isbn', models.CharField(max_length=150, null=True, verbose_name='ISBN', blank=True)),
                ('issn', models.CharField(max_length=150, null=True, verbose_name='ISSN', blank=True)),
                ('deposito_legal', models.CharField(max_length=150, null=True, verbose_name='Legal deposit', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'verbose_name_plural': 'Chapters of books',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.TextField(null=True, verbose_name='Title', blank=True)),
                ('fecha_de_inicio', models.DateField(null=True, verbose_name='Date', blank=True)),
                ('fecha_de_fin', models.DateField(null=True, verbose_name='End date', blank=True)),
                ('nombre_del_congreso', models.TextField(null=True, verbose_name='Name of the conference', blank=True)),
                ('ciudad_de_realizacion', models.CharField(max_length=500, null=True, verbose_name='City', blank=True)),
                ('autores', models.TextField(null=True, verbose_name='Authors', blank=True)),
                ('fecha', models.DateField(null=True, verbose_name='Date', blank=True)),
                ('ambito', models.CharField(max_length=50, null=True, verbose_name='Field of the conference', blank=True)),
                ('otro_ambito', models.CharField(max_length=250, null=True, verbose_name='Another area', blank=True)),
                ('deposito_legal', models.CharField(max_length=150, null=True, verbose_name='Legal deposit', blank=True)),
                ('publicacion_acta_congreso', models.CharField(max_length=100, null=True, verbose_name='Publication in conference proceedings', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'ordering': ['-fecha_de_inicio', 'titulo'],
                'verbose_name_plural': 'Conferences',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.CharField(max_length=1000, null=True, verbose_name='Name of the project', blank=True)),
                ('autores', models.TextField(null=True, verbose_name='Authors', blank=True)),
                ('fecha_de_inicio', models.DateField(null=True, verbose_name='Start date', blank=True)),
                ('fecha_de_fin', models.DateField(null=True, verbose_name='End date', blank=True)),
                ('duracion', models.IntegerField(null=True, verbose_name='Duration (in days)', blank=True)),
                ('ambito', models.CharField(max_length=50, null=True, verbose_name='Agreement area', blank=True)),
                ('otro_ambito', models.CharField(max_length=250, null=True, verbose_name='Another area', blank=True)),
                ('cod_segun_financiadora', models.CharField(max_length=100, null=True, verbose_name='Code acc. to the funding institution', blank=True)),
                ('cuantia_total', models.CharField(max_length=19, null=True, verbose_name='Total amount', blank=True)),
                ('cuantia_subproyecto', models.CharField(max_length=19, null=True, verbose_name='Sub-project amount', blank=True)),
                ('porcentaje_en_subvencion', models.CharField(max_length=19, null=True, verbose_name='Percentage as grant', blank=True)),
                ('porcentaje_en_credito', models.CharField(max_length=19, null=True, verbose_name='Percentage as credit', blank=True)),
                ('porcentaje_mixto', models.CharField(max_length=19, null=True, verbose_name='Mixed percentage', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'ordering': ['-fecha_de_inicio', 'titulo'],
                'verbose_name_plural': 'Agreements',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CVN',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cvn_file', models.FileField(upload_to=b'cvn/pdf', verbose_name='PDF')),
                ('xml_file', models.FileField(upload_to=b'cvn/xml', verbose_name='XML')),
                ('fecha', models.DateField(verbose_name='Date of CVN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.IntegerField(verbose_name='Status', choices=[(0, 'Actualizado'), (1, 'Caducado'), (2, 'NIF/NIE Incorrecto')])),
                ('is_inserted', models.BooleanField(default=False, verbose_name='Inserted')),
                ('user_profile', models.OneToOneField(to='core.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Normalized Curriculum Vitae',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.TextField(null=True, verbose_name='Publication title', blank=True)),
                ('fecha', models.DateField(null=True, verbose_name='Date', blank=True)),
                ('nombre_publicacion', models.TextField(null=True, verbose_name='Publication name', blank=True)),
                ('volumen', models.CharField(max_length=100, null=True, verbose_name='Volume', blank=True)),
                ('numero', models.CharField(max_length=100, null=True, verbose_name='Number', blank=True)),
                ('pagina_inicial', models.CharField(max_length=100, null=True, verbose_name='First page', blank=True)),
                ('pagina_final', models.CharField(max_length=100, null=True, verbose_name='Last page', blank=True)),
                ('autores', models.TextField(null=True, verbose_name='Authors', blank=True)),
                ('isbn', models.CharField(max_length=150, null=True, verbose_name='ISBN', blank=True)),
                ('issn', models.CharField(max_length=150, null=True, verbose_name='ISSN', blank=True)),
                ('deposito_legal', models.CharField(max_length=150, null=True, verbose_name='Legal deposit', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.TextField(null=True, verbose_name='Designation', blank=True)),
                ('fecha', models.DateField(null=True, verbose_name='Date', blank=True)),
                ('fecha_concesion', models.DateField(null=True, verbose_name='Concession date', blank=True)),
                ('num_solicitud', models.CharField(max_length=100, null=True, verbose_name='Request number', blank=True)),
                ('lugar_prioritario', models.CharField(max_length=100, null=True, verbose_name='Priority country', blank=True)),
                ('lugares', models.TextField(null=True, verbose_name='Countries', blank=True)),
                ('autores', models.TextField(null=True, verbose_name='Authors', blank=True)),
                ('entidad_titular', models.CharField(max_length=255, null=True, verbose_name='Owner entity', blank=True)),
                ('empresas', models.TextField(null=True, verbose_name='Companies', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'ordering': ['-fecha', 'titulo'],
                'verbose_name_plural': 'Intelectual Properties',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.CharField(max_length=1000, null=True, verbose_name='Name of the project', blank=True)),
                ('numero_de_investigadores', models.IntegerField(null=True, verbose_name='Number of researchers', blank=True)),
                ('autores', models.TextField(null=True, verbose_name='Authors', blank=True)),
                ('fecha_de_inicio', models.DateField(null=True, verbose_name='Start date', blank=True)),
                ('fecha_de_fin', models.DateField(null=True, verbose_name='End date', blank=True)),
                ('duracion', models.IntegerField(null=True, verbose_name='Duration (in days)', blank=True)),
                ('ambito', models.CharField(max_length=50, null=True, verbose_name='Project area', blank=True)),
                ('otro_ambito', models.CharField(max_length=250, null=True, verbose_name='Another area', blank=True)),
                ('cod_segun_financiadora', models.CharField(max_length=150, null=True, verbose_name='Code acc. to the funding institution', blank=True)),
                ('cuantia_total', models.CharField(max_length=19, null=True, verbose_name='Total amount', blank=True)),
                ('cuantia_subproyecto', models.CharField(max_length=19, null=True, verbose_name='Sub-project amount', blank=True)),
                ('porcentaje_en_subvencion', models.CharField(max_length=19, null=True, verbose_name='Percentage as grant', blank=True)),
                ('porcentaje_en_credito', models.CharField(max_length=19, null=True, verbose_name='Percentage as credit', blank=True)),
                ('porcentaje_mixto', models.CharField(max_length=19, null=True, verbose_name='Mixed percentage', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'ordering': ['-fecha_de_inicio', 'titulo'],
                'verbose_name_plural': 'Projects',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TesisDoctoral',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.TextField(null=True, verbose_name='Project title', blank=True)),
                ('fecha', models.DateField(null=True, verbose_name='Date of reading', blank=True)),
                ('autor', models.CharField(max_length=256, null=True, verbose_name='Author', blank=True)),
                ('universidad_que_titula', models.CharField(max_length=500, null=True, verbose_name='University issuing the qualification', blank=True)),
                ('codirector', models.CharField(max_length=256, null=True, verbose_name='Co-director', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user_profile', models.ManyToManyField(to='core.UserProfile', null=True, blank=True)),
            ],
            options={
                'ordering': ['-fecha', 'titulo'],
                'verbose_name_plural': 'Doctoral Thesis',
            },
            bases=(models.Model,),
        ),
    ]
